apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: skybyte-app-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: skybyte-app