apiVersion: v1
kind: Secret
metadata:
  name: api-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skybyte-app.labels" . | nindent 4 }}
type: Opaque
data:
  token: c2stc2t5Ynl0ZS1wcm9kLTdmM2M5YTJiMWU4ZDRhNmM=